In [1]:
import numpy as np


In [4]:
list1=[-1,1]

mermin=np.zeros([3,3])
print(mermin)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Merminの魔法陣

$$
 \begin{bmatrix}
   I\otimes\sigma_{z} & \sigma_{z}\otimes I & \sigma_{z}\otimes\sigma_{z} \\
   \sigma_{x}\otimes I & I\otimes\sigma_{x} & \sigma_{x}\otimes\sigma_{x} \\
   \sigma_{x}\otimes\sigma_{z} & \sigma_{z}\otimes\sigma_{z} & \sigma_{y}\otimes\sigma_{y}
  \end{bmatrix} \tag{4}
$$


に対して、パウリ行列の測定値は二値なので、

In [7]:
for pauli0 in list1:
    for paulix in list1:
        for pauliy in list1:
            for pauliz in list1:
                mermin[0][0]=pauli0*pauliz
                mermin[0][1]=pauliz*pauli0
                mermin[0][2]=pauliz*pauliz
                mermin[1][0]=paulix*pauli0
                mermin[1][1]=pauli0*paulix
                mermin[1][2]=paulix*paulix
                mermin[2][0]=paulix*pauliz
                mermin[2][1]=pauliz*paulix
                mermin[2][2]=pauliy*pauliy
                print(mermin)
                #print('\n')
                if(mermin[2][2]==-(mermin[0][2]*mermin[1][2])):
                    print("This is valid")
                else:
                    print("This is invalid")
                print('\n')
            

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
This is invalid


[[-1. -1.  1.]
 [ 1.  1.  1.]
 [-1. -1.  1.]]
This is invalid


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
This is invalid


[[-1. -1.  1.]
 [ 1.  1.  1.]
 [-1. -1.  1.]]
This is invalid


[[ 1.  1.  1.]
 [-1. -1.  1.]
 [-1. -1.  1.]]
This is invalid


[[-1. -1.  1.]
 [-1. -1.  1.]
 [ 1.  1.  1.]]
This is invalid


[[ 1.  1.  1.]
 [-1. -1.  1.]
 [-1. -1.  1.]]
This is invalid


[[-1. -1.  1.]
 [-1. -1.  1.]
 [ 1.  1.  1.]]
This is invalid


[[-1. -1.  1.]
 [-1. -1.  1.]
 [ 1.  1.  1.]]
This is invalid


[[ 1.  1.  1.]
 [-1. -1.  1.]
 [-1. -1.  1.]]
This is invalid


[[-1. -1.  1.]
 [-1. -1.  1.]
 [ 1.  1.  1.]]
This is invalid


[[ 1.  1.  1.]
 [-1. -1.  1.]
 [-1. -1.  1.]]
This is invalid


[[-1. -1.  1.]
 [ 1.  1.  1.]
 [-1. -1.  1.]]
This is invalid


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
This is invalid


[[-1. -1.  1.]
 [ 1.  1.  1.]
 [-1. -1.  1.]]
This is invalid


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
This is invalid


