In [40]:
import numpy as np
import math 
import random


def qubit():
    a=random.random()
    b=1-a
    c=math.sqrt(a)
    d=math.sqrt(b)
    e=np.array([[c],[d]])
    return(e)

a=qubit()
b=qubit()

print(a)
print(b)

print(a[0]*b[0])
print(a[0][0],a[1][0])

[[0.85409661]
 [0.52011439]]
[[0.31931557]
 [0.94764844]]
[0.27272634]
0.8540966129706168 0.5201143871420213


In [41]:
from numpy import linalg as LA

def multi(a,b):
    c=np.array([[a[0][0]*b[0][0]],[a[0][0]*b[1][0]],[a[1][0]*b[0][0]],[a[1][0]*b[1][0]]])
    return c

product=multi(a,b)
print(product)
#print(pow(product[0],2)+pow(product[1],2)+pow(product[2],2)+pow(product[3],2)) 
#print(product[0],product[1],product[2],product[3])

[[0.27272634]
 [0.80938332]
 [0.16608062]
 [0.49288559]]


In [42]:
rho=product*product.T
print(rho)

[[0.07437966 0.22074015 0.04529456 0.13442288]
 [0.22074015 0.65510137 0.13442288 0.39893338]
 [0.04529456 0.13442288 0.02758277 0.08185874]
 [0.13442288 0.39893338 0.08185874 0.2429362 ]]


When POVM element  $E_{1}:=0.4 |0 \rangle\langle 0|$

$E_{1}=\left(\begin{array}{cc} 
    0.4  & 0\\ 
    0&0
\end{array}\right)$

$E_{2}:=0.4 |+ \rangle\langle +|$

$E_{2}=\left(\begin{array}{cc} 
    \frac{1}{2}  &\frac{1}{2}\\ 
    \frac{1}{2}&\frac{1}{2}
\end{array}\right)$


$E_{1}\otimes E_{2}=E_{m}$とおくと

$E_{m}=\left(\begin{array}{cccc} 
    \frac{1}{5}  &\frac{1}{5}&0&0\\ 
    \frac{1}{5}&\frac{1}{5}&0&0\\
    0&0&0&0\\
    0&0&0&0
\end{array}\right)$

In [43]:
Em=np.array([[0.2,0.2,0,0],[0.2,0.2,0,0],[0,0,0,0],[0,0,0,0]])
print(Em)
print(Em[0][0])

[[0.2 0.2 0.  0. ]
 [0.2 0.2 0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]
0.2


In [44]:
Meas=np.dot(rho,Em)
print(rho*Em)
print(Meas)
print(Meas[0][0])

[[0.01487593 0.04414803 0.         0.        ]
 [0.04414803 0.13102027 0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
[[0.05902396 0.05902396 0.         0.        ]
 [0.1751683  0.1751683  0.         0.        ]
 [0.03594349 0.03594349 0.         0.        ]
 [0.10667125 0.10667125 0.         0.        ]]
0.05902396256655498


In [45]:
def prob(matrix,n):
    prob=0
    for i in range(0,n):
        prob+=matrix[i][i]
    return prob

pro=prob(Meas,3)
print(pro)

0.23419226664364168
