In [175]:
import numpy as np
from numpy import linalg as LA
import math 
import random


#任意次元のベクトルを生成する関数
#nは生成したい次元
def qubit(n):
    
    e=np.zeros(n,dtype='float64')
    
    e[0]=random.random()
    unf=1-e[0]
    
    for i in range(1,n-1):
        e[i]=random.uniform(0,unf)
        unf=unf-e[i]
    e[n-1]=unf
    
    return e


#ランダムなベクトルを規格化し、状態ベクトルになる．
def normal(e):
    n=e.size      #配列の次元を確認する関数
    
    E=np.zeros(n,dtype='float64')
    
    for i in range(0,n):
        E[i]=np.sqrt(e[i])
    return E


#ベクトルの間のテンソル積
def tensor(a,b):
    n1=a.size
    n2=b.size
    
    P=np.zeros(n1*n2,dtype='float64')
    for i in range(0,n1):
        for j in range(0,n2):
            P[i*n2+j]=a[i]*b[j]
    return P

#xはn1次元のベクトル、yはn2次元のベクトルとおく、zの次元はn1*n2である
x=normal(qubit(2))
y=normal(qubit(2))
z=tensor(x,y)

print('状態１は')
print(x)
print('状態2は')
print(y)
print('合成系の状態は')
print(z)


#ノルムの確認

print(LA.norm(x,2))

print(LA.norm(y,2))

print(LA.norm(z,2))

状態１は
[0.84222163 0.53913146]
状態2は
[0.87613675 0.48206264]
合成系の状態は
[0.73790132 0.40600358 0.47235289 0.25989513]
1.0
1.0
1.0


# 純粋状態の密度演算子

\begin{equation}
\rho_{1}=|n1\rangle\langle n1|,\rho_{2}=|n2\rangle\langle n2|,
\end{equation}


合成系の密度演算子は

\begin{equation}
\rho=|n1\otimes n2\rangle\langle n1\otimes n2|
\end{equation}


In [176]:
rho=np.dot(z,z.T)
print(rho)
print(z.T)

1.0
[0.73790132 0.40600358 0.47235289 0.25989513]


In [177]:
print(z.T)

[0.73790132 0.40600358 0.47235289 0.25989513]


In [178]:

#密度演算子を生成する関数
def density(a):
    dimension=a.size
    
    b=np.zeros([dimension,dimension],dtype='float64')
    for i in range(0,dimension):
        for j in range(0,dimension):
            b[i][j]=a[i]*a[j]
            
    return b


#トレースを計算する関数
def trace(a):
    sum=0;
    n=a[0].size
    for i in range(0,n):
        sum+=a[i][i]
    
    return sum
        

rho=density(z)
print(rho)
print(trace(rho))

[[0.54449836 0.29959058 0.34854982 0.19177696]
 [0.29959058 0.16483891 0.19177696 0.10551836]
 [0.34854982 0.19177696 0.22311725 0.12276222]
 [0.19177696 0.10551836 0.12276222 0.06754548]]
1.0


In [179]:
m1=np.array([1,0])
m2=np.array([0,1])
print(density(m1))

[[1. 0.]
 [0. 0.]]


# 計算基底における同時測定


計算基底について、

\begin{equation}
|00\rangle,  |01\rangle,  |10\rangle,  |11\rangle
\end{equation}

In [180]:
print(tensor(m1,m2))

[0. 1. 0. 0.]


In [185]:
#00 ketの確率を計算する

m=tensor(m1,m2)

def prob(base,state):
    z=np.dot(base,state)
    return math.pow(z,2)


#zは合成系の状態ベクトルである
prob1=prob(tensor(m1,m1),z)
prob2=prob(tensor(m1,m2),z)
prob3=prob(tensor(m2,m1),z)
prob4=prob(tensor(m2,m2),z)

print(prob1,prob2,prob3,prob4)
print(prob1+prob2+prob3+prob4)

#print(prob(m,z))

0.5444983619682794 0.16483890869705195 0.22311724838525626 0.06754548094941248
1.0


# 計算基底における部分測定

In [186]:
print(np.dot(m1,x))

0.8422216279966522


In [187]:
parcial1=np.dot(m1,x)*y

print(parcial1)
print(math.pow(LA.norm(parcial1,2),2))

[0.73790132 0.40600358]
0.7093372706653315


# 密度演算子による部分測定

In [196]:
rho_m=trace(density(y))
print(trace(rho_m*density(x)*density(m1)))

0.7093372706653313
