# エルミット演算子

作り方はgram－Schmidtのアルゴリズムと同じ

In [45]:
import numpy as np
from numpy import linalg as LA


dimension=2   #次元を指定する

def randomnumber(dimension):　　#ランダムな行列の生成
    return np.random.random((dimension,dimension))


def gram(a,b):   #規格化
    return ((np.dot(a,b)/np.dot(a,a))*a)


def hermatite(a): #複素共役
    return np.conjugate(a.T)


v=randomnumber(dimension)

u=np.zeros((dimension,dimension),dtype='float64')
u[0]=v[0]

x=0
sum=np.array([0,0],dtype='float64')

for a in range(1,dimension):
    for b in range(0,a):
        sum+=gram(u[b],v[a])
    u[a]=v[a]-sum
    
print(v)
print(u)



[[0.85520313 0.63946642]
 [0.94035398 0.05375801]]
[[ 0.85520313  0.63946642]
 [ 0.3114368  -0.41650619]]


In [46]:
e=np.zeros((dimension,dimension),dtype='float64')

for c in range(0,dimension):
    e[c]=u[c]/LA.norm(u[c],2)#·ord=2
    
print(e)

[[ 0.80086936  0.5988391 ]
 [ 0.5988391  -0.80086936]]


e:エルミット演算子

e(1),e(2).....e(n):ONB

# 状態







In [26]:
#psi=np.random.random((dimension))
#psi=e[0]
psi=np.array([e[0]])
print(psi)
print(LA.norm(psi,2))   #ノルム確認

[[0.79997157 0.6000379 ]]
1.0


# 密度演算子

ここで、Aの転置行列を求めるためには、配列のTプロパティ、または transpose()関数を使用します．

In [28]:
print(np.transpose(psi)) #転置行列の確認


[[0.79997157]
 [0.6000379 ]]


In [35]:
rho=np.dot(np.transpose(psi),psi)#密度演算子rho
print(rho)

[[0.63995452 0.48001326]
 [0.48001326 0.36004548]]


# 基底測定

2次元の場合、測定値 i_0 ,　i_1を得る確率が基底測定より、

In [41]:
i_0=np.square(LA.norm(np.dot(psi,e[0]),ord=1))
print(i_0)

1.0


In [42]:
i_1=np.square(LA.norm(np.dot(psi,e[1]),ord=1))
print(i_1)

5.207714569623086e-31


# Bron's ruleによる測定結果