In [4]:
import qutip as qt
from qutip import *
import numpy as np

In [5]:
Qobj([[1],[2],[3],[4],[5]])

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]

In [6]:
basis(5,3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [7]:
coherent(5,0.5-0.5j)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.7788017 +0.j        ]
 [ 0.38939142-0.38939142j]
 [ 0.        -0.27545895j]
 [-0.07898617-0.07898617j]
 [-0.04314271+0.j        ]]

In [8]:
q = destroy(4)
x = sigmax()
q + 5

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

In [9]:
x * x

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]